name: Bundle Size Analysis

on:
  pull_request:
    branches: [main, master]

permissions:
  pull-requests: write  # Required to post comments on PRs

jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js and pnpm
      uses: ./.github/actions/setup-node-pnpm

    - name: Check and report bundle size
      uses: andresz1/size-limit-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        build_script: build
        skip_step: install  # We already installed dependencies
        package_manager: pnpm